### PR TITLE
Release OpenMSX 0.3.2

### PR DESCRIPTION
**Pull request by DevanWolf**
I decided to make a fixed and more compact version of OpenMSX as 0.3.2 which includes the following:
- Update: Optimized MIDI data for all songs to reduce file size
- Update: Replace 'Big Man Boogie' with fixed version of 'Keep on Rolling'
And some more text file corrections

### CODE REVIEW

**Comment by Wuzzy2** [comment]
This PR is problematic because tries to do many unrelated things at once (including bumping the release number!!!), which is probably why it has been ignored for years.

I suggest to split up this PR on a per-feature / per-bugfix basis. And drop the "release" portion of it entirely; there are other things that need fixing as well (see #7, #8, #9).

**Comment by nielsmh** [comment]
Also, what exactly does this "optimized MIDI data" entail? It can mean a lot of things, and I'd like some documentation on what was actually done. (Sure I could go find/write a tool to compare the tracks, but that seems overkill.)

**Comment by Wuzzy2** [comment]
I have more questions. It is about this:

> Update: Replace 'Big Man Boogie' with fixed version of 'Keep on Rolling'

But why? What was wrong with the old track? What do you mean with “fixed version”? Is one of the current tracks broken?

**Comment by Wuzzy2** [comment]
Okay, so have done some research on this. So it appears to me the problem this PR attempts to fix are real.
I have found an older attempt of DevanWolf to fix this here, with a better justification:

> I noticed the MIDI data for all of the songs in OpenMSX have unoptimized data in them. Like the error found in tttheme2.mid the track with the jazz guitar in it is supposed to be channel 8 not 6, that I fixed. I decided to do this to help reduce file size. During this process, I realized during this MIDI editing process that 'Keep on Rolling' now plays correctly, so like "Replace 'Big Man Boogie' with fixed version of 'Keep on Rolling'" (Also changed source download link in readme file)

Source: https://dev.openttdcoop.org/issues/8623

I'm still not sure why this optimization is neccessary, but I am definitely not a MIDI expert, don't ask me!

Also, I have now figured out the rationale behind 'Keep on rolling', see #12.
I support using the 'Keep on rolling' track in OpenMSX now.

I suggest to do the following:

* Close this PR as being too chaotic
* Open new PRs to do the tasks cleanly separated, instead of doing everything at once. Specifically:
    * Bring back 'Keep on rolling' track (#12) in a new PR
    * Do the MIDI optimization stuff (if neccessary) in another PR
    * Text file cleanup is handled in #11
* Review if this commit makes sense and make a PR if it does: https://github.com/OpenTTD/OpenMSX/pull/1/commits/d14bfa2aa051dcdfd94daa9e4845dd57f7cc4878

**Comment by LordAro** [comment]
Going to go ahead and close this now, as most things have been superceded by others. Feel free to open new PR(s) for the relevant remaining things

**Pull request closed without merging**
