### PR TITLE
Credit musicians in readme

### PR DESCRIPTION
**Pull request by Wuzzy2**
This adds the music authors in the readme.
I also removed non-author data from themes.list.

### CODE REVIEW

**Comment by Wuzzy2** [comment]
This PR needs updating now ... Stay tuned!

**Comment by Wuzzy2** [comment]
Okay, this PR is ready again.

**Comment by LordAro** [comment]
Use rebases, rather than merging (and also correct commit message style)

**Comment by Wuzzy2** [comment]
I hope this is better now.

**Review by orudge — APPROVED** [review]

**Pull request merged**
