### PR TITLE
Prepare for 0.4.0 release

### PR DESCRIPTION
**Pull request by LordAro**
Nothing groundbreaking. Will probably please @Wuzzy2

### CODE REVIEW

**Comment by Wuzzy2** [comment]
It would still be nice if all the MIDI files were verified for technical errors (#17).
If I only knew how to do that … :-( Do we have a MIDI expert aroud here?
Since that verification didn't happen yet, I caution against calling it 1.0.0. Maybe 0.4.0?

At least I know that all tracks work on my system but there might be errors that only manifest on some systems / MIDI implementations. Or there might be data errors (corrupted data) in the tracks or something like that. IDK, I'm not a MIDI expert.

**Comment by LordAro** [comment]
No one's reported any errors in 10 years, I feel it's unlikely there's anything significant in there

**Comment by LordAro** [comment]
Not exactly blocking a release, anyway

**Comment by Wuzzy2** [comment]
Oh, you should probably consult @kamnet as well. Read this for reference:

https://www.tt-forums.net/viewtopic.php?p=1242639#p1242639

@kamnet appears to disapprove of a 1.0.0 release right now.

(But I guess a 0.4.0 release would be fine.)

**Review by orudge — DISMISSED** [review]
I see no real reason not to call this 1.0.0 - if anyone identifies any technical deficiencies in the MIDI files, a 1.0.1 is easy enough to do, and if we change things around more significantly, then a 1.1.0 bump might be justified.

**Comment by Wuzzy2** [comment]
Yeah, OK. It is not THAT big of a deal, I also think it is unlikely that any serious mistakes are in the MIDI files left. I just think that @kamnet, who is literally the founder of OpenMSX, should have a word in that. Just saying. ;-)

**Comment by kevinfields777** [comment]
Truthfully? I'd prefer a 1.0.0 release be one that is 100% userbase-contributed with no music loaned from outside sources. 

Realistically? I don't know if that will ever happen, largely because there's almost no overlap between OpenTTD players who also create or can contribute original MIDI works, and most players really don't care. They'd rather be able to use MP3, MP4 or FLAC files that they can create with easily obtainable tools. 

But I'm kind of an old school person when it comes to numbering. 1.0.0 represents a "final" product that is complete and has accomplished all it set out to do. And while I like all of the music that is in OpenMSX right now, it doesn't feel complete, and not deserving of a 1.0.0 title. I'm perfectly happy with leaving it at 0.3.1 right now.  

With that said, this isn't really my project to say one way or another. I initiated it, but it's always been a community project. My involvement has been to find the music, evaluate it as best as I can to make sure it's as good of quality as I think it should be and make recommendations. That effort has largely come to an end. And I have never had any control over things like finding and fixing errors in music files, or its publication and distribution. If others feel it needs a 1.0.0 version, it's not within my power or will to stop that.

**Comment by Wuzzy2** [comment]
I agree. Sort of.

If the version number is going to be 1.0.0, then the BaNaNaS description should be updated as well because it mentions OpenMSX being a “work of progress”.
Although I'm afraid no “community set” of music is going to be created anytime soon. Meaning OpenMSX would be stuck pre-1.0.0 for years.

There are good arguments for 0.4.0 and 1.0.0. I no longer have a strong opinion about either.

I REALLY wish we had someone who could verify the MIDI files tho. Not a release blocker, but still. Let me dream … ;-)

But no matter which version number it is going to be, I strongly opine there should be [i]some[/i] release, mostly due to the long-overdue technical cleanup lately. I strongly disagree with keeping OpenMSX intentionally stuck at 0.3.1 forever.

So either 0.4.0 or 1.0.0.

**Comment by kevinfields777** [comment]
Since I can't remember stuff ATM, have there been changes since 0.3.1 was released? If so, then a version bump is warranted.

**Review by TrueBrain — APPROVED** [review]

**Pull request merged**
